### PR TITLE
Styling for buttons

### PR DESCRIPTION
**Pull request by Marketionist**
**This pull request adds styling for buttons**

Details:
- added styling for Upload locators button

### CODE REVIEW

**Comment by Marketionist** [comment]
@alexkrechik please review

**Comment by alexkrechik** [comment]
@Marketionist could you please decrease "Upload Locators" button height, like in file attached, but with properly vertically aligned ?
screen shot 2016-08-10 at 6 31 00 pm
 text ?

**Comment by Marketionist** [comment]
Done. @alexkrechik please review

**Comment by alexkrechik** [comment]
LGTM

**Pull request merged**
